"""

Revision ID: ed96809f837c
Revises:
Create Date: 2026-01-05 09:36:29.337187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import utils


# revision identifiers, used by Alembic.
revision: str = 'ed96809f837c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'ACTIVE', 'FOUND', 'CLOSED', 'BLOCKED', name='petmissingnoticestatuschoice').create(op.get_bind())
    sa.Enum('HEALTHY', 'WOUNDED', 'SCARED', name='pethealthconditionchoice').create(op.get_bind())
    sa.Enum('NEW', 'ACTIVE', 'RETURNED', 'CLOSED', 'BLOCKED', name='petfoundnoticestatuschoice').create(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'UNKNOW', name='petsexchoice').create(op.get_bind())
    sa.Enum('DOG', 'CAT', 'BIRD', 'OTHER', name='petspecieschoice').create(op.get_bind())
    sa.Enum('NEW', 'ACTIVE', 'ADOPTED', 'CLOSED', 'BLOCKED', name='petadoptionnoticestatuschoice').create(op.get_bind())
    op.create_table(
        'users',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('username', sa.String(length=150), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('email', sa.String(length=150), nullable=True),
        sa.Column('phone_number', sa.String(length=11), nullable=False),
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
        sa.Column('is_blocked', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone_number'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'messages',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('recipient_id', sa.BigInteger(), nullable=False),
        sa.Column('sender_id', sa.BigInteger(), nullable=False),
        sa.Column('text', sa.String(length=100), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['recipient_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sender_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'notifications',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('recipient_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=30), nullable=False),
        sa.Column('text', sa.String(length=100), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['recipient_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'pet_adoption_notices',
        sa.Column(
            'status',
            postgresql.ENUM(
                'NEW', 'ACTIVE', 'ADOPTED', 'CLOSED', 'BLOCKED', name='petadoptionnoticestatuschoice', create_type=False
            ),
            nullable=False,
        ),
        sa.Column('owner_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=150), nullable=False),
        sa.Column('pet_name', sa.String(length=30), nullable=False),
        sa.Column(
            'pet_species',
            postgresql.ENUM('DOG', 'CAT', 'BIRD', 'OTHER', name='petspecieschoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_breed', sa.String(length=50), nullable=True),
        sa.Column('pet_color', sa.String(length=30), nullable=False),
        sa.Column('pet_special_marks', sa.String(length=100), nullable=True),
        sa.Column(
            'pet_sex',
            postgresql.ENUM('MALE', 'FEMALE', 'UNKNOW', name='petsexchoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_age', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_table(
        'pet_found_notices',
        sa.Column(
            'status',
            postgresql.ENUM(
                'NEW', 'ACTIVE', 'RETURNED', 'CLOSED', 'BLOCKED', name='petfoundnoticestatuschoice', create_type=False
            ),
            nullable=False,
        ),
        sa.Column('finder_id', sa.BigInteger(), nullable=True),
        sa.Column('found_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('found_location', utils.geoalchemy.PointField(), nullable=False),
        sa.Column('pet_was_with_collar', sa.Boolean(), nullable=False),
        sa.Column(
            'pet_health_condition',
            postgresql.ENUM('HEALTHY', 'WOUNDED', 'SCARED', name='pethealthconditionchoice', create_type=False),
            nullable=False,
        ),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=150), nullable=False),
        sa.Column('pet_name', sa.String(length=30), nullable=False),
        sa.Column(
            'pet_species',
            postgresql.ENUM('DOG', 'CAT', 'BIRD', 'OTHER', name='petspecieschoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_breed', sa.String(length=50), nullable=True),
        sa.Column('pet_color', sa.String(length=30), nullable=False),
        sa.Column('pet_special_marks', sa.String(length=100), nullable=True),
        sa.Column(
            'pet_sex',
            postgresql.ENUM('MALE', 'FEMALE', 'UNKNOW', name='petsexchoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_age', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['finder_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_table(
        'pet_missing_notices',
        sa.Column(
            'status',
            postgresql.ENUM(
                'NEW', 'ACTIVE', 'FOUND', 'CLOSED', 'BLOCKED', name='petmissingnoticestatuschoice', create_type=False
            ),
            nullable=False,
        ),
        sa.Column('owner_id', sa.BigInteger(), nullable=False),
        sa.Column('lost_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('lost_location', utils.geoalchemy.PointField(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=150), nullable=False),
        sa.Column('pet_name', sa.String(length=30), nullable=False),
        sa.Column(
            'pet_species',
            postgresql.ENUM('DOG', 'CAT', 'BIRD', 'OTHER', name='petspecieschoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_breed', sa.String(length=50), nullable=True),
        sa.Column('pet_color', sa.String(length=30), nullable=False),
        sa.Column('pet_special_marks', sa.String(length=100), nullable=True),
        sa.Column(
            'pet_sex',
            postgresql.ENUM('MALE', 'FEMALE', 'UNKNOW', name='petsexchoice', create_type=False),
            nullable=False,
        ),
        sa.Column('pet_age', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_table(
        'users_locations',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('location', utils.geoalchemy.PointField(), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'location', name='user_id_location_unique_constraint'),
    )
    op.create_table(
        'users_passwords',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_passwords')
    op.drop_geospatial_index(
        'idx_users_locations_location', table_name='users_locations', postgresql_using='gist', column_name='location'
    )
    op.drop_geospatial_table('users_locations')
    op.drop_geospatial_index(
        'idx_pet_missing_notices_lost_location',
        table_name='pet_missing_notices',
        postgresql_using='gist',
        column_name='lost_location',
    )
    op.drop_geospatial_table('pet_missing_notices')
    op.drop_geospatial_index(
        'idx_pet_found_notices_found_location',
        table_name='pet_found_notices',
        postgresql_using='gist',
        column_name='found_location',
    )
    op.drop_geospatial_table('pet_found_notices')
    op.drop_table('pet_adoption_notices')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('users')
    sa.Enum('NEW', 'ACTIVE', 'ADOPTED', 'CLOSED', 'BLOCKED', name='petadoptionnoticestatuschoice').drop(op.get_bind())
    sa.Enum('DOG', 'CAT', 'BIRD', 'OTHER', name='petspecieschoice').drop(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'UNKNOW', name='petsexchoice').drop(op.get_bind())
    sa.Enum('NEW', 'ACTIVE', 'RETURNED', 'CLOSED', 'BLOCKED', name='petfoundnoticestatuschoice').drop(op.get_bind())
    sa.Enum('HEALTHY', 'WOUNDED', 'SCARED', name='pethealthconditionchoice').drop(op.get_bind())
    sa.Enum('NEW', 'ACTIVE', 'FOUND', 'CLOSED', 'BLOCKED', name='petmissingnoticestatuschoice').drop(op.get_bind())
    # ### end Alembic commands ###
